WinkelCo\MercadoLibreApi\Entity\SellerAddress:
  exclusion_policy: NONE
  properties:
    id:
      type: "integer"
    address_line:
      type: "string"
    city:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\Localization"
    comment:
      type: "string"
    country:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\Localization"
    latitude:
      type: "float"
    longitude:
      type: "float"
    search_location:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\SearchLocation"
    state:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\Localization"
    zip_code:
      type: "string"
