WinkelCo\MercadoLibreApi\Entity\SellerTransaction:
  exclusion_policy: NONE
  properties:
    canceled:
      type: "integer"
    completed:
      type: "integer"
    period:
      type: "string"
    ratings:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\Rating"
    total:
      type: "integer"
