WinkelCo\MercadoLibreApi\Entity\BuyerReputation:
  exclusion_policy: NONE
  properties:
    canceled_transactions:
      type: "integer"
    tags:
      type: "array"
    transactions:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\BuyerTransaction"
