WinkelCo\MercadoLibreApi\Entity\CategoryPrediction:
  exclusion_policy: NONE
  properties:
    path_from_root:
      type: "array<WinkelCo\\MercadoLibreApi\\Entity\\CategoryPrediction>"
    prediction_probability:
      type: "float"
    shipping_modes:
      type: "array"
