WinkelCo\MercadoLibreApi\Entity\StatusAction:
  exclusion_policy: NONE
  properties:
    allow:
      type: "boolean"
    codes:
      type: "array"
    immediate_payment:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\ImmediatePayment"
