WinkelCo\MercadoLibreApi\Entity\SellerReputation:
  exclusion_policy: NONE
  properties:
    level_id:
      type: "string"
    power_seller_status:
      type: "string"
    transactions:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\SellerTransaction"
