WinkelCo\MercadoLibreApi\Entity\Category:
  exclusion_policy: NONE
  properties:
    id:
      type: "string"
    name:
      type: "string"
    path_from_root:
      type: "array<WinkelCo\\MercadoLibreApi\\Entity\\Category>"
