WinkelCo\MercadoLibreApi\Entity\Status:
  exclusion_policy: NONE
  properties:
    billing:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\StatusAction"
    buy:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\StatusAction"
    confirmed_email:
      type: "boolean"
    immediate_payment:
      type: "boolean"
    list:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\StatusAction"
    mercadoenvios:
      type: "string"
    mercadopago_account_type:
      type: "string"
    mercadopago_tc_accepted:
      type: "boolean"
    required_action:
      type: "string"
    sell:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\StatusAction"
    site_status:
      type: "string"
    user_type:
      type: "string"
