WinkelCo\MercadoLibreApi\Entity\Address:
  exclusion_policy: NONE
  properties:
    address:
      type: "string"
    city:
      type: "string"
    state:
      type: "string"
    zip_code:
      type: "string"
