WinkelCo\MercadoLibreApi\Entity\SearchLocation:
  exclusion_policy: NONE
  properties:
    city:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\Localization"
    neighborhood:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\Localization"
    state:
      type: "WinkelCo\\MercadoLibreApi\\Entity\\Localization"
